web:
  restart: always
  build: ./web
  # Expose ports without publishing them to the host machine 
  expose:
    - "8000"
  links:
    - postgres:postgres 
  env_file: .env
  volumes:
    - ./web:/usr/src/app
  command: /usr/local/bin/gunicorn mycms.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx
  # Expose ports and publish them to the host machine 
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  ports:
    - "5432:5432"
